#**Sentiment Analysis on IMDB Movie Reviews**

Zaidurrohman
21/477632/PA/20678

#Import Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/Pembelajaran Mesin - Final Project/IMDB-Dataset.csv')
df.head(10)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [ ]:
df.shape

(50000, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [ ]:
print(df.isnull().sum())

review       0
sentiment    0
dtype: int64


Terlihat bahwa tidak terdapat null value pada dataset

In [ ]:
df.sentiment.value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

Terlihat bahwa dataset balance antara label positif dan negatif

In [ ]:
df.sentiment.replace('positive',1,inplace=True)
df.sentiment.replace('negative',0,inplace=True)
df.head(10)

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1
5  Probably my all-time favorite movie, a story o...          1
6  I sure would like to see a resurrection of a u...          1
7  This show was an amazing, fresh & innovative i...          0
8  Encouraged by the positive comments about this...          0
9  If you like original gut wrenching laughter yo...          1

In [ ]:
df.review[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

#Data Preprocessing

##Remove HTML tags

In [ ]:
import re # regex

def removeHTML(text):
  cleaned = re.compile(r'<.*?>')
  return re.sub(cleaned,'',text)

df.review = df.review.apply(removeHTML)
df.review[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wo

terlihat pada baris terakhir df.review[0], string "\<br />\<br />" yang merupakan tag HTML dihilangkan

##Remove special characters

In [ ]:
def is_special(text):
  rem = ''
  for i in text:
    # isalnum() bernilai True jika semua karakter adalah alphanumeric (a-z,A-Z,0-9)
    if i.isalnum():
      rem = rem + i
    else:
      rem = rem + ' '
  return rem

df.review = df.review.apply(is_special)
df.review[0]

'One of the other reviewers has mentioned that after watching just 1 Oz episode you ll be hooked  They are right  as this is exactly what happened with me The first thing that struck me about Oz was its brutality and unflinching scenes of violence  which set in right from the word GO  Trust me  this is not a show for the faint hearted or timid  This show pulls no punches with regards to drugs  sex or violence  Its is hardcore  in the classic use of the word It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary  It focuses mainly on Emerald City  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  Em City is home to many  Aryans  Muslims  gangstas  Latinos  Christians  Italians  Irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away I would say the main appeal of the show is due to the fact that it goes where other shows wo

terlihat pada baris terakhir df.review[0], frasa "viewing....thats" berubah menjadi "viewing&nbsp;&nbsp;&nbsp;&nbsp;thats" dengan menghilangkan karakter '.' (titik).

##Convert to lowercase

In [ ]:
def to_lower(text):
  return text.lower()

df.review = df.review.apply(to_lower)
df.review[0]

'one of the other reviewers has mentioned that after watching just 1 oz episode you ll be hooked  they are right  as this is exactly what happened with me the first thing that struck me about oz was its brutality and unflinching scenes of violence  which set in right from the word go  trust me  this is not a show for the faint hearted or timid  this show pulls no punches with regards to drugs  sex or violence  its is hardcore  in the classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wo

Terlihat bahwa semua huruf besar telah diubah ke huruf kecil

##Tokenization and remove stopwords

Stopword merupakan kata yang kurang memiliki makna atau kurang merepresentasikan isi suatu teks, sehingga perlu dihilangkan

In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def rem_stopwords(text):
  stop_words = set(stopwords.words('english'))
  words = word_tokenize(text)
  return [w for w in words if w not in stop_words]

df.review = df.review.apply(rem_stopwords)
df.review[0]

['one',
 'reviewers',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 'hooked',
 'right',
 'exactly',
 'happened',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'word',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focuses',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'many',
 'aryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'away',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'da

##Stemming
Stemming adalah proses mengubah suatu kata ke bentuk kata dasarnya. Contoh: "watched" menjadi "watch"

In [ ]:
from nltk.stem import SnowballStemmer

def stem_text(text):
  ss = SnowballStemmer('english')
  return " ".join([ss.stem(w) for w in text])

df.review = df.review.apply(stem_text)
df.review[0]

df.head(10)

review  sentiment
0  one review mention watch 1 oz episod hook righ...          1
1  wonder littl product film techniqu unassum old...          1
2  thought wonder way spend time hot summer weeke...          1
3  basic famili littl boy jake think zombi closet...          0
4  petter mattei love time money visual stun film...          1
5  probabl time favorit movi stori selfless sacri...          1
6  sure would like see resurrect date seahunt ser...          1
7  show amaz fresh innov idea 70 first air first ...          0
8  encourag posit comment film look forward watch...          0
9  like origin gut wrench laughter like movi youn...          1

#Feature Extraction

##Bag of Words



In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
X = np.array(df.iloc[:,0].values)
y = np.array(df.sentiment.values)
CV = CountVectorizer(max_features = 1000)
X = CV.fit_transform(df.review).toarray()
print("X.shape = ", X.shape)
print("y.shape = ", y.shape)

X.shape =  (50000, 1000)
y.shape =  (50000,)


In [ ]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=9)
print("Train shapes : X = {}, y = {}".format(X_train.shape, y_train.shape))
print("Test shapes : X = {}, y = {}".format(X_test.shape, y_test.shape))

Train shapes : X = (40000, 1000), y = (40000,)
Test shapes : X = (10000, 1000), y = (10000,)


#Build the Classifier Models

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

##Decision Tree classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
params = {
    'criterion':['gini','entropy'],
    'splitter':['best', 'random']
}

dec_tree = DecisionTreeClassifier()

grid = GridSearchCV(estimator=dec_tree,
                    param_grid=params,
                    cv=5,
                    verbose=1)

grid.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'splitter': ['best', 'random']},
             verbose=1)

In [ ]:
grid.best_params_

{'criterion': 'entropy', 'splitter': 'best'}

In [ ]:
dec_tree_best = DecisionTreeClassifier(criterion='gini', splitter='best')
dec_tree_best.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
pred = dec_tree_best.predict(X_test)

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.72      0.72      0.72      5023
           1       0.72      0.71      0.71      4977

    accuracy                           0.72     10000
   macro avg       0.72      0.72      0.72     10000
weighted avg       0.72      0.72      0.72     10000



##Naive Bayes classifier

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import RepeatedStratifiedKFold

In [ ]:
np.logspace(0, -9, num=10)

array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07,
       1.e-08, 1.e-09])

In [ ]:
cv_method = RepeatedStratifiedKFold(n_splits=5,
                                    n_repeats=3,
                                    random_state=999)

In [ ]:
from sklearn.preprocessing import PowerTransformer

params_NB = {
    'var_smoothing': np.logspace(0,-9,num=10)
}

model_NB = GaussianNB()

grid_NB = GridSearchCV(estimator=model_NB,
                     param_grid=params_NB,
                     cv=cv_method,
                     verbose=1,
                     scoring='accuracy')

Data_transformed = PowerTransformer().fit_transform(X_test)

grid_NB.fit(Data_transformed, y_test)

Fitting 15 folds for each of 10 candidates, totalling 150 fits


GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=3, n_splits=5, random_state=999),
             estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07,
       1.e-08, 1.e-09])},
             scoring='accuracy', verbose=1)

In [ ]:
grid_NB.best_params_

{'var_smoothing': 0.001}

In [ ]:
predict_test = grid_NB.predict(Data_transformed)

print(classification_report(y_test, predict_test))

              precision    recall  f1-score   support

           0       0.82      0.82      0.82      5023
           1       0.82      0.81      0.82      4977

    accuracy                           0.82     10000
   macro avg       0.82      0.82      0.82     10000
weighted avg       0.82      0.82      0.82     10000



#Kesimpulan

Dari hasil eksperimen, setelah dilakukan hyperparameter tuning, diperoleh hasil bahwa model klasifikasi menggunakan **Naive Bayes** memiliki performa yang lebih baik dibandingkan dengan model klasifikasi menggunakan Decision Tree.